name: Cypress Tests

on:
  push:                  # Trigger the workflow on push
    branches:
      - main
  pull_request:          # Trigger the workflow on PRs
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest # Environment to run the tests

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Fetch code from the repository

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Install Node.js
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run test 
          wait-on: http://localhost:3000
