name: Cypress Tests

on:
  push:                  # Trigger the workflow on push
    branches:
      - main
  pull_request:          # Trigger the workflow on PRs
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest # Environment to run the tests

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Fetch code from the repository

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Install Node.js
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run test 
          wait-on: http://localhost:3000
          
      - name: Upload Test Results
        if: always() # Runs even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: |
            cypress/screenshots   # Upload screenshots on failures
            cypress/videos        # Upload videos recorded during tests
            cypress/logs          # Upload logs if any

      # Step 6: Upload Debug Logs for Analysis
      - name: Upload Debug Logs
        if: failure() # Only runs if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: debug-logs
          path: /home/runner/.npm/_logs

      # Step 7: Notify Test Results (Optional)
      - name: Notify on Failure
        if: failure() # Send notifications if tests fail
        run: echo "Cypress tests failed. Check logs and screenshots for debugging."
