name: Cypress Tests with Allure Report

on:
  push:
    branches:
      - main  # Replace 'main' with your desired branch name

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the desired Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Cypress tests with Allure
      - name: Run Cypress tests
        run: |
          npm install -g allure-commandline --save-dev # Install Allure
          npx cypress run --browser=chrome --headed --spec "cypress/e2e/**/*.cy.js" --reporter mocha-allure-reporter
        continue-on-error: true  # Allows workflow to proceed even if this step fails

      # Step 5: Generate Allure Report (Runs always, regardless of previous steps' success)
      - name: Generate Allure Report
        if: always() # Ensures this step runs even if the Cypress tests fail
        run: |
          npx allure generate allure-results --clean -o allure-report

      # Step 6: Clean up gh-pages branch before publishing
      - name: Cleanup gh-pages branch
        if: always()
        run: |
          git fetch origin gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages
          git rm -rf .
          git commit -m "Cleanup old reports" || echo "No changes to commit"
          git push origin gh-pages

      # Step 7: Publish Allure report using GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        if: always() # Ensures this step runs even if the Cypress tests fail
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GHTOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages  # Specify the branch to use for GitHub Pages
          force_orphan: true        # Force-create a new commit without history
